name: Add Supabase Secret Variables

on:
   workflow_dispatch:
    inputs:
      logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
            - info
            - warning
            - debug
            
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:

      - name: Use Secrets in Environment Variables
        run: |
            echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
            echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
            
        env:
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}


      - name: Use Secrets Directly
        run: |
          echo "Using the secret SUPABASE ANON API key: ${{ secrets.VITE_SUPABASE_ANON_KEY }}"
          echo "Using the secret SUPABASE URL: ${{ secrets.VITE_SUPABASE_URL }}"

      - name: Mask Secrets in Logs
        run: |
          echo "The secret SUPABASE ANON API key is masked: ${{ secrets.VITE_SUPABASE_ANON_KEY }}"
          echo "The secret SUPABASE URL is masked: ${{ secrets.VITE_SUPABASE_URL }}"
# gh workflow run .github/workflows/secret-variables.yml --ref work_flow