name: Add Supabase Secret Variables

on:
   workflow_dispatch:
    inputs:
      logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
            - info
            - warning
            - debug
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Secrets in Environment Variables
        env:
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        run: |
          echo "Using the secret SUPABASE ANON API key: $VITE_SUPABASE_ANON_KEY"
          echo "Using the secret SUPABASE URL: $VITE_SUPABASE_URL"

      - name: Use Secrets Directly
        run: |
          echo "Using the secret SUPABASE ANON API key: ${{ secrets.VITE_SUPABASE_ANON_KEY }}"
          echo "Using the secret SUPABASE URL: ${{ secrets.VITE_SUPABASE_URL }}"

      - name: Mask Secrets in Logs
        run: |
          echo "The secret SUPABASE ANON API key is masked: ${{ secrets.VITE_SUPABASE_ANON_KEY }}"
          echo "The secret SUPABASE URL is masked: ${{ secrets.VITE_SUPABASE_URL }}"
